---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kube-monitoring-config
  namespace: fluxcdnginx
spec:
  interval: 15s
  path: ./monitoring/configs
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-monitoring
  timeout: 1m0s
  wait: true
