---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: fluxnginxkust
  namespace: fluxcdnginx
spec:
  interval: 15s
  path: ./deploy
  prune: true
  sourceRef:
    kind: GitRepository
    name: fluxnginxsrc
