---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: fluxnginxsrc
  namespace: fluxcdnginx
spec:
  interval: 15s
  ref:
    branch: master
  url: https://github.com/aayushknoldus03/fluxnginx
